### ISSUE TITLE
Export list with newline breaks

### ISSUE THREAD

**Issue by caiomcoliveira** [rbonifacio/rascal-js#2]
export {
  Util,
  Alert,
  Button,
  Carousel,
  Collapse,
  Dropdown,
  Modal,
  Popover,
  Scrollspy,
  Tab,
  Toast,
  Tooltip
}

This won't parse.
See file:
bootstrap-4-dev/js/src/index.js... found an error at line 40, column 7

**Comment by rbonifacio** [comment]
@caiomcoliveira @helpmehelpus , did you fix this issue?

**Comment by caiomcoliveira** [comment]
Fixed on last commit  dad4c5cab635d4edb01868019f2fc3027654c63b

**Comment by caiomcoliveira** [comment]
Didn't fix properly
Will re-check

**Comment by caiomcoliveira** [comment]
Fixed a0ebac07dd47e5b7154cd2f7b2030128870b0fd3

**Comment by caiomcoliveira** [comment]
Fixed a0ebac07dd47e5b7154cd2f7b2030128870b0fd3
